# Select the installed NextOS toolchain explicitly; never pin an older sysroot.
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)
if(NOT DEFINED ENV{NEXTOS_TOOLCHAIN})
    message(FATAL_ERROR "Set NEXTOS_TOOLCHAIN to the current NextOS toolchain directory")
endif()
set(_nextos "$ENV{NEXTOS_TOOLCHAIN}")
set(CMAKE_C_COMPILER "${_nextos}/bin/aarch64-libreelec-linux-gnu-gcc")
set(CMAKE_CXX_COMPILER "${_nextos}/bin/aarch64-libreelec-linux-gnu-g++")
set(CMAKE_SYSROOT "${_nextos}/aarch64-libreelec-linux-gnu/sysroot")
set(CMAKE_FIND_ROOT_PATH "${CMAKE_SYSROOT}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
set(ENV{PKG_CONFIG_SYSROOT_DIR} "${CMAKE_SYSROOT}")
set(ENV{PKG_CONFIG_LIBDIR} "${CMAKE_SYSROOT}/usr/lib/pkgconfig:${CMAKE_SYSROOT}/usr/share/pkgconfig")
set(ENV{PKG_CONFIG_PATH} "")
